name: Quality checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel the current workflow running if a new one is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: read
  pull-requests: write
  actions: write
  issues: write

jobs:
  test-and-quality-checks:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Run lint
        run: pnpm lint

      - name: Run type check
        run: pnpm tsc

      - name: Run unit and integration tests coverage
        run: pnpm test:ci

      - name: 'Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2

      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          vitest-config-path: vite.config.mts
          result-type: lines
          gist-token: ${{ secrets.GIST_TOKEN }}
          gist-url: https://gist.github.com/vhlongon/b1f395b2532fc512e4b3ce4fa294e1b9
          upload-badge: true
          badge-text: Test coverage

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
